Repository pckv/kompis, pull requests merged in 2019-11, with the labels that each got.

#25 Implement JSON web token authorization
  pom.xml
  src/main/java/me/pckv/kompis/Application.java
  src/main/java/me/pckv/kompis/WebMvcContext.java
  src/main/java/me/pckv/kompis/annotation/Authorized.java
  src/main/java/me/pckv/kompis/annotation/LoggedIn.java
  src/main/java/me/pckv/kompis/controller/UserController.java
  src/main/java/me/pckv/kompis/data/User.java
  src/main/java/me/pckv/kompis/data/UserRepository.java
  src/main/java/me/pckv/kompis/security/AuthorizationAttributeResolver.java
  src/main/java/me/pckv/kompis/security/AuthorizationInterceptor.java
  src/main/java/me/pckv/kompis/security/JwtManager.java
  src/main/java/me/pckv/kompis/security/JwtProperties.java
  src/main/java/me/pckv/kompis/security/PasswordUtil.java
  src/main/java/me/pckv/kompis/service/UserService.java
  src/main/resources/application.properties.template
Labels: api

#30 Move repositories to separate branch
  src/main/java/me/pckv/kompis/repository/ListingRepository.java
  src/main/java/me/pckv/kompis/repository/UserRepository.java
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: refactor

#31 Cleanup user controller and service
  src/main/java/me/pckv/kompis/controller/UserController.java
  src/main/java/me/pckv/kompis/data/User.java
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: api, refactor

#34 Create tests for MVC and setup Travis postgresql driver and configuration
  .gitignore
  .travis.yml
  pom.xml
  src/main/resources/application.properties
  src/test/java/me/pckv/kompis/UserControllerTest.java
  src/test/resources/application-travis.properties
  src/test/resources/application.properties
Labels: project, test

#33 Create listing service and controller
  src/main/java/me/pckv/kompis/controller/ListingController.java
  src/main/java/me/pckv/kompis/data/Listing.java
  src/main/java/me/pckv/kompis/repository/ListingRepository.java
  src/main/java/me/pckv/kompis/repository/UserRepository.java
  src/main/java/me/pckv/kompis/service/ListingService.java
Labels: api

#32 Update readme so codacy will be happy :)
  README.md
Labels: project, refactor

#36 Add method attribute resolver for injecting listings into controller endpoint
  src/main/java/me/pckv/kompis/WebMvcContext.java
  src/main/java/me/pckv/kompis/controller/ListingController.java
  src/main/java/me/pckv/kompis/resolver/AuthorizationAttributeResolver.java
  src/main/java/me/pckv/kompis/resolver/ListingAttributeResolver.java
  src/main/java/me/pckv/kompis/service/ListingService.java
Labels: api

#38 Fix JSON web token expiration checking
  src/main/java/me/pckv/kompis/security/JwtManager.java
Labels: bug

#41 Add Autowired to bean constructors
  src/main/java/me/pckv/kompis/WebMvcContext.java
  src/main/java/me/pckv/kompis/controller/ListingController.java
  src/main/java/me/pckv/kompis/controller/UserController.java
  src/main/java/me/pckv/kompis/resolver/AuthorizationAttributeResolver.java
  src/main/java/me/pckv/kompis/resolver/ListingAttributeResolver.java
  src/main/java/me/pckv/kompis/security/AuthorizationInterceptor.java
  src/main/java/me/pckv/kompis/security/JwtManager.java
  src/main/java/me/pckv/kompis/service/ListingService.java
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: refactor

#39 Set dev as the default spring profile
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: refactor

#43 Changed notations in location class
  src/main/java/me/pckv/kompis/data/Location.java
Labels: bug

#44 Document the API and redefine endpoints
  README.md
Labels: documentation, refactor

#42 Refactoring controllers to follow the API documentation
  src/main/java/me/pckv/kompis/controller/ListingController.java
  src/main/java/me/pckv/kompis/controller/UserController.java
  src/main/java/me/pckv/kompis/data/Listing.java
  src/main/java/me/pckv/kompis/service/ListingService.java
  src/main/java/me/pckv/kompis/service/UserService.java
  src/test/java/me/pckv/kompis/UserControllerTest.java
Labels: api, refactor

#51 Added documentation on api
  README.md
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: bug, documentation

#54 Add response messages to response status exception throw cases
  src/main/java/me/pckv/kompis/security/AuthorizationInterceptor.java
  src/main/java/me/pckv/kompis/service/ListingService.java
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: api, bug

#53 Fixed codacy issues in readme.md
  README.md
Labels: documentation

#50 Check that the user of a JWT exists on authentication
  src/main/java/me/pckv/kompis/repository/UserRepository.java
  src/main/java/me/pckv/kompis/security/AuthorizationInterceptor.java
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: bug

#56 Delete user fix
  src/main/java/me/pckv/kompis/repository/ListingRepository.java
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: bug

#55 Validate fields for data entities
  src/main/java/me/pckv/kompis/controller/ListingController.java
  src/main/java/me/pckv/kompis/controller/UserController.java
  src/main/java/me/pckv/kompis/data/Listing.java
  src/main/java/me/pckv/kompis/data/User.java
  src/main/java/me/pckv/kompis/error/CustomGlobalExceptionHandler.java
  src/test/java/me/pckv/kompis/UserControllerTest.java
Labels: api, database

#59 Update `DELETE /users/current` documentation.
  README.md
  src/main/java/me/pckv/kompis/controller/UserController.java
Labels: documentation

#60 Fix error fields in validate error
  src/main/java/me/pckv/kompis/error/CustomGlobalExceptionHandler.java
Labels: api

#61 Added location compability with frontend
  src/main/java/me/pckv/kompis/data/Listing.java
  src/main/java/me/pckv/kompis/data/Location.java
  src/main/java/me/pckv/kompis/service/ListingService.java
Labels: api

#62 Add Assignee class that allows us to store assignee location
  src/main/java/me/pckv/kompis/controller/ListingController.java
  src/main/java/me/pckv/kompis/data/Assignee.java
  src/main/java/me/pckv/kompis/data/Listing.java
  src/main/java/me/pckv/kompis/service/ListingService.java
Labels: api

#63 Add firebase support and sending notifications when users are assigned
  .gitignore
  README.md
  pom.xml
  src/main/java/me/pckv/kompis/FcmInitializer.java
  src/main/java/me/pckv/kompis/controller/UserController.java
  src/main/java/me/pckv/kompis/data/User.java
  src/main/java/me/pckv/kompis/service/ListingService.java
  src/main/java/me/pckv/kompis/service/UserService.java
Labels: api, database, enhancement

#64 Update API documentation to include location
  README.md
Labels: documentation
